name: "Setup CI Device"
description: "Installs tools and sets up environment for the CI "
runs:
  using: "composite"
  steps:
    - name: setup flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: "3.27.4"

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
    - name: 'Setup the CI device by installing dependencies'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake libgtk-3-dev

        flutter config --enable-linux-desktop
        sudo apt-get install -y xvfb
        cargo install flutter_rust_bridge_codegen@2.10.0