name: "Setup CI Device"
description: "Installs tools and sets up environment for the CI "
runs:
  using: "composite"
  steps:
    - name: update pacakge manager
      shell: bash
      run: apt-get update

    - name: 'Setup yq'
      uses: dcarbone/install-yq-action@v1

    - name: Set up Node.js
      shell: bash
      run: |
        apt-get install nodejs -y

    - name: Set up Node.js two electric boogaloo
      uses: actions/setup-node@v4
      with:
        node-version: "22.16.0"

    - name: git exception for flutter
      shell: bash
      run: git config --global --add safe.directory ${RUNNER_TOOL_CACHE}/flutter/3.32.2/stable/flutter

    - uses: flutter-actions/setup-flutter@v4
      with:
        channel: stable
        version: 3.32.2



    # - name: Install Rust
    #   uses: actions-rs/toolchain@v1
    #   with:
    #     toolchain: stable
    #     profile: minimal
    #     override: true

    - name: "Setup the CI device by installing dependencies"
      shell: bash
      run: |
        apt-get install -y cmake libgtk-3-dev ninja-build pkg-config clang libasound2

        flutter config --enable-linux-desktop
        apt-get install -y xvfb
        cargo install flutter_rust_bridge_codegen@2.10.0
