name: flutter_mldsa
description: "Pointycastle interface implentations for MlDsa using bindings to RustCrypto implementation of ml-dsa"
#  version: '0.0.0' is a placeholder
version: '0.0.0' 
homepage: https://github.com/rivtechnologies/flutter_mldsa
environment:
  sdk: ^3.6.2
  flutter: ">=3.3.0"
dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_rust_bridge: 2.10.0
  plugin_platform_interface: ^2.0.2
  pointycastle: ^4.0.0
dev_dependencies:
  ffi: ^2.1.3
  ffigen: ^13.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter
flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true
