name: update changelog
description: Update changelog from tag annotations
runs:
  using: "composite"
  steps:
    - name: Check if current tag is annotated
      id: tag_check
      shell: bash
      run: |

        tag_name=${GITHUB_REF#refs/tags/}
        echo "$tag_name"
        tag_commit=$(git rev-parse "$tag_name^{commit}")

        if [ -z "$tag_commit" ]; then
          echo "No tag found pointing there"
          exit 1
        fi

        type=$(git cat-file -t "$tag_name")
        
        if [ "$type" = "commit" ]; then
          echo "$tag_name is a LIGHTWEIGHT tag"
          exit 1
        elif [ "$type" = "tag" ]; then
          sh scripts/update-changelog.sh
        fi
