name: Working on the tag
description: This is going to do the necessary work involving the tag
runs:
  using: "composite"
  steps:
    - name: Check if current tag is annotated
      id: tag_check
      shell: bash
      run: |
        tag=$(git describe --tags --exact-match HEAD 2>/dev/null \ || git tag --points-at HEAD)
        tag_name=$(git describe --tags)


        tag=$(git tag --points-at HEAD)
        if [ -z "$tag" ]; then
          echo "No tag found pointing at HEAD"
          exit 1
        fi

        type=$(git cat-file -t "$tag")
        
        if [ "$type" = "commit" ]; then
          echo "$tag is LIGHTWEIGHT"
          exit 1
        fi

        if git cat-file -t "$tag" | grep -q '^tag$'; then
          sh scripts/tag-work.sh
        fi
