name: Publish Tagged Commits
descriptions: "This will fetch the publisher information and publish the new package version"
runs:
  using: "composite"
  steps:
    - name: Run the publishing script to take the cred token from secrets and get rid of it afterwards.
      shell: bash
      run: |
        tag_name=${GITHUB_REF#refs/tags/}
        version=${tag_name#\v}

        yq eval ".version = \"$version\"" -i pubspec.yaml
