name: "Test and Setup CI Device"
description: "Installs tools and sets up environment for the CI "
runs:
  using: "composite"
  steps:
    - name: generate rust bindings
      shell: bash
      run: |   
        flutter_rust_bridge_codegen generate

    - name: rust-side tests
      shell: bash
      run: |  
        cd rust
        cargo test -- --show-output
        cargo build --release

    - name: flutter-side tests
      shell: bash
      run: |
        flutter --version
        cd example
        flutter clean
        flutter pub get

        xvfb-run --auto-servernum -- flutter test -d linux integration_test/master_integration_test.dart
        


