name: Setup Wasm Test
description: Setup the Wasm Integration Test
runs:
  using: "composite"
  steps:
    - name: Set up ChromeDriver
      uses: nanasess/setup-chromedriver@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        profile: minimal
        override: true
        
    - name: Build Web & MV
      shell: bash
      run: |
        sudo mv -f chromedriver /usr/local/bin/chromedriver
        cd example
        CHROMEDRIVER=chromedriver make build-web
        
        

