name: all-tests

on: push

jobs:
  setup-and-tests:
    name: Generating bindings
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.4'
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            ninja-build \
            pkg-config \
            libgtk-3-dev \
            liblzma-dev \
            libstdc++6 \
            libgl1-mesa-dev \
            libegl1-mesa-dev \
            libxcb1-dev \
            libx11-dev \
            libgdk-pixbuf2.0-dev \
            libssl-dev

      - name: Enable Flutter desktop
        run: flutter config --enable-linux-desktop
      - name: Run Flutter pub get
        run: flutter pub get

      - name: Build or test Rust code
        working-directory: rust
        run: cargo fetch
        
      - name: Install flutter_rust_bridge_codegen
        run: cargo install flutter_rust_bridge_codegen 
        
      - name: Install flutter_rust_bridge_codegen
        run: flutter_rust_bridge_codegen generate 
        
      - name: Test the Rust code
        working-directory: rust
        run:  cargo test -- --show-output 

      - name: Test the Dart code
        working-directory: example
        run:  flutter test -d linux integration_test/master_integration_test.dart

