name: Publish Tagged Commits to main
on:
  push:
    tags:
      - 'v*'
jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image: rust:1.87
    permissions:
      contents: read 
      id-token: write 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true
          ref: ${{ github.ref }}

      - name: Setup
        uses: ./.github/actions/setup-dependencies

      - name: tests
        uses: ./.github/actions/integration-test
      
      - name: Integration tests for wasm
        uses: ./.github/actions/integration-test-wasm

      - name: Update Changelog
        uses: ./.github/actions/update-changelog 
        
      - name: Pubspec Version Update
        uses: ./.github/actions/pubspec-version-update
        
      - uses: dart-lang/setup-dart@v1
      
        
      - name: publish
        uses: ./.github/actions/publish-tagged-commit
