name: Publish Tagged Commits to main

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup CI Device action
        uses: ./.github/actions/integration_test
        
      - name: Publish Action
        uses: ./.github/actions/publish-tagged-commit