name: Publish Tagged Commits to main

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.4"
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Run CI Device Setup Workflow
        run: |
          echo "Running the setup script"
          sh scripts/setup.sh
          if [ "${{ job.status }}" != "success" ]; then exit 0; fi

      - name: Run Linux integration test in virtual display and test Dart Code
        working-directory: example
        run: |
          xvfb-run --auto-servernum -- flutter test -d linux integration_test/master_integration_test.dart

      - name: Setup and Test wortkflow
        uses: |
          if [ "${{ job.status }}" != "success" ]; then exit 0; fi

      - name: Setup and Test wortkflow
        uses: |
          mkdir -p ~/.config/dart
          echo "${{ secrets.PUB_CREDENTIALS }}" > ~/.config/dart/pub-credentials.json

      - name: Publish to pub.dev
        run: dart pub publish

      - name: Remove credentials file
        run: |
          shred -u ~/.config/dart/pub-credentials.json || rm -f ~/.config/dart/pub-credentials.json

      - name: Clear in-memory env var
        env:
          # override the secret with an empty string
          PUB_CREDENTIALS: ""
        run: |
          echo "PUB_CREDENTIALS was cleared"

      - name: Mask any stray echoes
        run: |
          echo "::add-mask::${{ secrets.PUB_CREDENTIALS }}"
