name: Publish Tagged Commits to main
on:
  push:
    tags:
      - 'v*'
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read 
      id-token: write 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true
          ref: ${{ github.ref }}
      - name: Necessary tag work
        uses: ./.github/actions/tag-work 
      - uses: dart-lang/setup-dart@v1
      - name: Setup CI Device action
        uses: ./.github/actions/integration-test
        
      - name: Publish Action
        uses: ./.github/actions/publish-tagged-commit
        with:
          pub_cred: ${{ secrets.PUB_CREDENTIALS }}
