name: Publish Tagged Commits to main
on:
  push:
    tags:
      - 'v*'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup CI Device action
        uses: ./.github/actions/integration-test
        
      - name: Publish Action
        uses: ./.github/actions/publish-tagged-commit
        with:
          pub_cred: ${{ secrets.PUB_CREDENTIALS }}
