name: master-integration-test

on:
  push:
    branches:
      - main
    tags-ignore:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  test:
    container:
      image: rust:1.86
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup-dependencies

      - name: Integration tests
        uses: ./.github/actions/integration-test

      - name: Integration tests for wasm
        uses: ./.github/actions/integration-test-wasm
