name: master-integration-test

on:
  push:
    branches:
      - main
    tags-ignore:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/catthehacker/ubuntu:rust-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup-dependencies

      - name: Integration tests
        uses: ./.github/actions/integration-test

      - name: Integration tests for wasm
        uses: ./.github/actions/integration-test-wasm

      - name: Exit Failure
        if: ${{ failure() }}
        run: exit 1
