name: master-integration-test

on:
  push:
    branches:
      - main
    tags-ignore:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  setup-and-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Pubspec Version Update
        uses: ./.github/actions/pubspec-version-update
      - name: Run CI Device Setup Workflow
        uses: ./.github/actions/integration-test
